/*
 * This file is generated by jOOQ.
*/
package cn.microservice.config.pojo.mysql;


import cn.microservice.config.pojo.mysql.tables.Property;
import cn.microservice.config.pojo.mysql.tables.records.PropertyRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>signit_config</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<PropertyRecord, Long> IDENTITY_PROPERTY = Identities0.IDENTITY_PROPERTY;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PropertyRecord> KEY_PROPERTY_PRIMARY = UniqueKeys0.KEY_PROPERTY_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<PropertyRecord, Long> IDENTITY_PROPERTY = createIdentity(Property.PROPERTY, Property.PROPERTY.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<PropertyRecord> KEY_PROPERTY_PRIMARY = createUniqueKey(Property.PROPERTY, "KEY_property_PRIMARY", Property.PROPERTY.ID);
    }
}
