/*
 * This file is generated by jOOQ.
*/
package cn.microservice.config.pojo.mysql;


import cn.microservice.config.pojo.mysql.tables.Property;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in signit_config
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>signit_config.property</code>.
     */
    public static final Property PROPERTY = cn.microservice.config.pojo.mysql.tables.Property.PROPERTY;
}
