/*
 * This file is generated by jOOQ.
*/
package cn.microservice.config.pojo.mysql.tables.records;


import cn.microservice.config.pojo.mysql.tables.Property;

import java.util.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PropertyRecord extends UpdatableRecordImpl<PropertyRecord> implements Record9<Long, String, String, String, String, Integer, Boolean, Date, Date> {

    private static final long serialVersionUID = 489025242;

    /**
     * Setter for <code>signit_config.property.id</code>. 数据库自增id
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>signit_config.property.id</code>. 数据库自增id
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>signit_config.property.application</code>.
     */
    public void setApplication(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>signit_config.property.application</code>.
     */
    public String getApplication() {
        return (String) get(1);
    }

    /**
     * Setter for <code>signit_config.property.profile</code>.
     */
    public void setProfile(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>signit_config.property.profile</code>.
     */
    public String getProfile() {
        return (String) get(2);
    }

    /**
     * Setter for <code>signit_config.property.label</code>.
     */
    public void setLabel(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>signit_config.property.label</code>.
     */
    public String getLabel() {
        return (String) get(3);
    }

    /**
     * Setter for <code>signit_config.property.property</code>.
     */
    public void setProperty(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>signit_config.property.property</code>.
     */
    public String getProperty() {
        return (String) get(4);
    }

    /**
     * Setter for <code>signit_config.property.version</code>.
     */
    public void setVersion(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>signit_config.property.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>signit_config.property.active</code>.
     */
    public void setActive(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>signit_config.property.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>signit_config.property.created_datetime</code>. 创建时间
     */
    public void setCreatedDatetime(Date value) {
        set(7, value);
    }

    /**
     * Getter for <code>signit_config.property.created_datetime</code>. 创建时间
     */
    public Date getCreatedDatetime() {
        return (Date) get(7);
    }

    /**
     * Setter for <code>signit_config.property.modified_datetime</code>. 修改时间
     */
    public void setModifiedDatetime(Date value) {
        set(8, value);
    }

    /**
     * Getter for <code>signit_config.property.modified_datetime</code>. 修改时间
     */
    public Date getModifiedDatetime() {
        return (Date) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, String, String, Integer, Boolean, Date, Date> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, String, String, Integer, Boolean, Date, Date> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Property.PROPERTY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Property.PROPERTY.APPLICATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Property.PROPERTY.PROFILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Property.PROPERTY.LABEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Property.PROPERTY.PROPERTY_;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Property.PROPERTY.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field7() {
        return Property.PROPERTY.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field8() {
        return Property.PROPERTY.CREATED_DATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field9() {
        return Property.PROPERTY.MODIFIED_DATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getApplication();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getProfile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLabel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getProperty();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value7() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value8() {
        return getCreatedDatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value9() {
        return getModifiedDatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropertyRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropertyRecord value2(String value) {
        setApplication(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropertyRecord value3(String value) {
        setProfile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropertyRecord value4(String value) {
        setLabel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropertyRecord value5(String value) {
        setProperty(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropertyRecord value6(Integer value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropertyRecord value7(Boolean value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropertyRecord value8(Date value) {
        setCreatedDatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropertyRecord value9(Date value) {
        setModifiedDatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PropertyRecord values(Long value1, String value2, String value3, String value4, String value5, Integer value6, Boolean value7, Date value8, Date value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PropertyRecord
     */
    public PropertyRecord() {
        super(Property.PROPERTY);
    }

    /**
     * Create a detached, initialised PropertyRecord
     */
    public PropertyRecord(Long id, String application, String profile, String label, String property, Integer version, Boolean active, Date createdDatetime, Date modifiedDatetime) {
        super(Property.PROPERTY);

        set(0, id);
        set(1, application);
        set(2, profile);
        set(3, label);
        set(4, property);
        set(5, version);
        set(6, active);
        set(7, createdDatetime);
        set(8, modifiedDatetime);
    }
}
