/*
 * This file is generated by jOOQ.
*/
package cn.microservice.config.pojo.mysql.tables.pojos;


import java.io.Serializable;
import java.util.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Property implements Serializable {

    private static final long serialVersionUID = -290250014;

    private Long    id;
    private String  application;
    private String  profile;
    private String  label;
    private String  property;
    private Integer version;
    private Boolean active;
    private Date    createdDatetime;
    private Date    modifiedDatetime;

    public Property() {}

    public Property(Property value) {
        this.id = value.id;
        this.application = value.application;
        this.profile = value.profile;
        this.label = value.label;
        this.property = value.property;
        this.version = value.version;
        this.active = value.active;
        this.createdDatetime = value.createdDatetime;
        this.modifiedDatetime = value.modifiedDatetime;
    }

    public Property(
        Long    id,
        String  application,
        String  profile,
        String  label,
        String  property,
        Integer version,
        Boolean active,
        Date    createdDatetime,
        Date    modifiedDatetime
    ) {
        this.id = id;
        this.application = application;
        this.profile = profile;
        this.label = label;
        this.property = property;
        this.version = version;
        this.active = active;
        this.createdDatetime = createdDatetime;
        this.modifiedDatetime = modifiedDatetime;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getApplication() {
        return this.application;
    }

    public void setApplication(String application) {
        this.application = application;
    }

    public String getProfile() {
        return this.profile;
    }

    public void setProfile(String profile) {
        this.profile = profile;
    }

    public String getLabel() {
        return this.label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public String getProperty() {
        return this.property;
    }

    public void setProperty(String property) {
        this.property = property;
    }

    public Integer getVersion() {
        return this.version;
    }

    public void setVersion(Integer version) {
        this.version = version;
    }

    public Boolean getActive() {
        return this.active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public Date getCreatedDatetime() {
        return this.createdDatetime;
    }

    public void setCreatedDatetime(Date createdDatetime) {
        this.createdDatetime = createdDatetime;
    }

    public Date getModifiedDatetime() {
        return this.modifiedDatetime;
    }

    public void setModifiedDatetime(Date modifiedDatetime) {
        this.modifiedDatetime = modifiedDatetime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Property (");

        sb.append(id);
        sb.append(", ").append(application);
        sb.append(", ").append(profile);
        sb.append(", ").append(label);
        sb.append(", ").append(property);
        sb.append(", ").append(version);
        sb.append(", ").append(active);
        sb.append(", ").append(createdDatetime);
        sb.append(", ").append(modifiedDatetime);

        sb.append(")");
        return sb.toString();
    }
}
